version: '3'

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      - SWAGGER_JSON=/api/swagger.yaml
    volumes:
      - ./swagger/api.yaml:/api/swagger.yaml:ro
    network_mode: "host"
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    network_mode: "host"
  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    network_mode: "host"
    depends_on:
      - prometheus
